version: 0.2

env:
  variables:
    ECR_REPOSITORY: 086997486593.dkr.ecr.us-east-1.amazonaws.com/test-ecr

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo ${ECR_REPOSITORY}
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ECR_REPOSITORY}
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t teruya-ecs-container .
      - docker tag teruya-ecs-container:latest ${ECR_REPOSITORY}:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push ${ECR_REPOSITORY}:latest
      - echo Build completed on `date`
      - echo Creating imagedefinitions.json...
      - |
        echo '[
          {
            "name": "teruya-ecs-container",
            "imageUri": "'${ECR_REPOSITORY}':latest"
          }
        ]' > imagedefinitions.json
      - echo imagedefinitions.json created.

artifacts:
  files:
    - imagedefinitions.json
